config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "splash#index"

  resources :users

  resources :groups, only: [:index, :new, :create] do
    resources :expenses, only: [:index, :new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    #   return unless user.admin?
    can :manage, :all, user_id: user.id
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :group_expenses, dependent: :destroy
  has_many :groups, through: :group_expenses

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0, message: 'Amount must be greater than 0' }
  validates :groups, presence: true, length: { minimum: 1, message: 'Expense must belong to at least one group' }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups
  has_many :expenses

  validates :name, presence: true, length: { minimum: 3, message: 'must be at least 3 characters long' }
  validates :email, presence: true, length: { minimum: 3, maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6, maximum: 25 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  include CanCan::ControllerAdditions

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: exception.message
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @group = Group.find_by(user: current_user, id: params[:group_id])
    @expenses = @group.expenses.order(created_at: :desc)
  end

  def new
    @expense = Expense.new
    @groups = Group.all.where(user: current_user)
  end

  def create
    @expense = Expense.new(expense_params)
    @groups = params[:groups] || []
    @groups.each do |id|
      group = Group.find(id) unless id == ''
      @expense.groups << group unless group.nil?
    end
    @expense.author = current_user
    respond_to do |format|
      if @expense.save
        format.html { redirect_to group_expenses_path, notice: 'Expenditure successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html do
          redirect_to group_expenses_path, status: :unprocessable_entity,
                                           notice: 'Expenditure not added. All fields mandatory'
        end
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource :groups

  def index
    @groups = Group.all.where(user: current_user).includes(:expenses)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if user_signed_in?
      redirect_to groups_path
    else
      render :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/group_expenses_helper.rb
module GroupExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>" class="bg-white p-2 m-2">
  <div class="d-flex flex-row justify-content-between  align-items-center ">
  <div>
    <i class="bi bi-cart4 me-3" style="font-size: 30px;"></i>
    <%= expense.name %>
  </div> 

  <strong><p class="text-secondary">$
    <%= expense.amount %>
  </p></strong>
  </div>
  <p class="ms-4 ps-4 text-muted" style="font-size: 10px;">
    <%= expense.created_at.to_date.strftime("%d %b %Y")  %>
  </p>
</div>

app/views/expenses/_form.html.erb
<%= form_for @expense, url: group_expenses_path do |form| %>
<div class="d-flex flex-column">
  <% if expense.errors.any? %>
    <div style="color: red" class="alert alert-warning alert-dismissible fade show" role="alert">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <div class="my-2">
    <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>

  <div class="my-2">
    <%= form.text_field :amount, placeholder: "Amount", class: "form-control" %>
  </div>

  <% if @groups.any? %>
    <div class="my-2">
      <%= form.label :groups, "Select Category" %>
      <%= select_tag :groups, options_for_select(@groups.map { |group| [group.name, group.id] }), multiple: true %>
    </div>
 <% end %>

  <%= form.submit "SAVE", class: "btn text-white bottomArea"%>
<% end %>
</div>

app/views/expenses/index.html.erb
<div class="headerSignin d-flex flex-row   p-2 justify-content-between">
  <%= link_to groups_path do %>
    <h3 class="d-flex align-items-center"><i class="bi bi-arrow-left text-white "></i></h3>
  <% end %>
  <h5 class="d-flex align-items-center ">TRANSACTIONS</h5>
  <%= link_to new_group_expense_path, class: "d-flex align-items-center" do %>
    <h3><i class="bi bi-plus text-white"></i></h3>
  <% end %>
</div>

<div id="expenses" class="bg-light" style="height:60%;">
  
  <div class="d-flex flex-row mb-2 py-2 px-4 justify-content-between bg-white">
    <%= @group.name %>
    <strong><p>$<%= @group.expenses.sum(:amount) %></p></strong>
  </div>
  <% if @expenses.empty? %>
    <p class= 'd-block p-2  '>No expenses yet</p>
  <% end%>
    <% @expenses.each do |expense| %>    
      <%= render expense %> 
    <% end  %>
</div>

<div class="bottomArea ">
<%= link_to "ADD NEW TRANSACTION", new_group_expense_path, class: "border border-white " %>
</div>

app/views/expenses/new.html.erb
<div class="headerSignin d-flex flex-row mb-4 p-2 justify-content-between">

  <%= link_to group_expenses_path do %>
    <h3 class="d-flex align-items-center"><i class="bi bi-arrow-left text-white "></i></h3>
  <% end %>

  <h5 class="d-flex align-items-center ">New Transaction</h5>
  
  <%= link_to destroy_user_session_path, method: :delete do %>
    <h3 class="d-flex align-items-center"><i class="bi bi-power text-white "></i></h3>
  <% end %>
</div>

<%= render "form", expense: @expense %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
<div class="d-flex flex-column">
  <% if group.errors.any? %>
    <div style="color: red" class="alert alert-warning alert-dismissible fade show" role="alert">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this Category from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

    </div>
  <% end %>

  <div class="my-2">
    <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>

  <div class="my-2">
    <%= form.text_field :icon, placeholder: "Icon URL", class: "form-control" %>
  </div>

  <div class="my-2">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

    <strong><%= form.submit "SAVE", class: "btn text-white bottomArea" %></strong>
<% end %>
</div>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="bg-white p-2 m-2">
  <div class="d-flex flex-row justify-content-between  align-items-center ">
  <p class="text-black-50">
    <img src=<%= group.icon %> alt=<%= group.name %> class="img-thumbnail groupIcon">
    <%= group.name %>
  </p>
  <p class="text-secondary">
   <strong>$</strong>
    <%= group.expenses.sum(:amount) %>
  </p>
  </div>
  <p class="ms-4 ps-4 text-muted" style="font-size: 10px;">
    <%= group.created_at.to_date.strftime("%d %b %Y")  %>
  </p>
</div>

app/views/groups/index.html.erb
<div class="headerSignin d-flex flex-row mb-4 p-2 justify-content-between">
<%= link_to destroy_user_session_path, method: :delete do %>
  <h3 class="d-flex align-items-center"><i class="bi bi-power text-white "></i></h3>
<% end %>
<h5 class="d-flex align-items-center ">CATEGORIES</h5>
<%= link_to new_group_path, class: "d-flex align-items-center" do %>
  <h3><i class="bi bi-plus text-white"></i></h3>
<% end %>
</div>

<div id="groups" class="bg-light groupBox" >
  <% @groups.each do |group| %>
    <%= link_to group_expenses_path(group.id), class: 'd-block p-2  ' do %>
      <%= render group %>
    <% end %>
  <% end %>
</div>

<div class="bottomArea">
  <%= link_to "ADD NEW CATEGORY", new_group_path, class: "border border-white mt-2  " %>
</div>

app/views/groups/new.html.erb
<div class="headerSignin d-flex flex-row mb-4 p-2 justify-content-between">
  <%= link_to groups_path do %>
    <h3 class="d-flex align-items-center"><i class="bi bi-arrow-left text-white "></i></h3>
  <% end %>
  <h5 class="d-flex align-items-center ">Add New Category</h5>
  <%= link_to destroy_user_session_path, method: :delete do %>
    <h3 class="d-flex align-items-center"><i class="bi bi-power text-white "></i></h3>
  <% end %>
</div>

<%= render "form", group: @group %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <% if notice %> 
    <%= notice %>
  <% end %>
  <% if alert %> 
    <%= alert %>
  <% end %>  
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Money Minder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <% if notice%>
      <%= render partial: "layouts/alerts" %>      
    <% end %> 
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/splash/index.html.erb
<div class="splashScreen bg-primary.bg-gradient">
    <h1 class="splash">Money Minder</h1>
    <div class="text-center d-grid gap-2 col-6 mx-auto splashbutton">
        <%= link_to "LOG IN", new_user_session_path, class: "btn text-dark login_button" %>
        <%= link_to "SIGN UP", new_user_registration_path, class: "btn text-dark login_button" %>
    </div>
</div>

app/views/users/index.html.erb
<div>
<% @users.each do |user| %>
  <div>
    <%= user.name %>
  </div>
<% end %>
</div>